"""
Pydantic schemas for the Claude API test endpoint.

Defines request and response models for testing the Anthropic Claude
API integration, confirming the API key is valid and the connection works.
"""

from pydantic import BaseModel


class ClaudeTestRequest(BaseModel):
    """
    Request schema for the Claude API test endpoint.

    Contains a prompt to send to Claude for verification.
    Defaults to a medical question to confirm the AI responds
    with relevant USMLE-related content.
    """

    # The text prompt to send to Claude (defaults to a medical question)
    prompt: str = "Explain the pathophysiology of heart failure in one paragraph."


class ClaudeTestResponse(BaseModel):
    """
    Response schema for the Claude API test endpoint.

    Returns the AI-generated response along with model info
    and a status indicator confirming the integration works.
    """

    # The text response generated by Claude
    response: str

    # The model identifier used (e.g., "claude-sonnet-4-20250514")
    model: str

    # Status of the API call: "success" if completed without errors
    status: str
